version: '3'
services:

#  inner:
#    container_name: ${DOMAIN_PATH}inner
#    env_file: .env
#    image: nginxproxy/nginx-proxy:dev
#    expose:
#      - "80"
#    restart: always
#    environment:
#      - DEFAULT_HOST=${DOMAIN_PATH}.com
#      - VIRTUAL_HOST=outer.bar.com
#      - VIRTUAL_PATH=/studip/
#      - VIRTUAL_DEST=/
#    logging:
#      driver: local #or "none" or "local"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro # allow to read running dockers
#      #- ./nginx/test:/etc/nginx/conf.d # to see the config output
#    networks:
#      - topDomainProxy


  app:
    env_file: .env
    image: jwilder/whoami
    environment:
      #- VIRTUAL_HOST=${DOMAIN_PATH}.com
      #- VIRTUAL_PATH=/whoami
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/${DOMAIN_PATH}/whoami
      - VIRTUAL_DEST=/
    networks:
      - topDomainProxy



  frontend:
    env_file: .env
    build: Frontend
    #command: npm run web
    command: npm run deploy:web:local
    volumes:
      - ./Frontend/app:/usr/app/
      - ./Frontend/app/node_modules:/usr/app/node_modules
      #- ./Frontend/app/web-build:/usr/app/web-build
    expose:
      - ${FRONTEND_PORT}
      - 19006
    environment:
      - BACKEND_URL=${DOMAIN_PRE}://${HOST}/${DOMAIN_PATH}/${BACKEND_PATH}
      - BASE_PATH=${DOMAIN_PATH}/${FRONTEND_PATH}/
      #- VIRTUAL_HOST=${DOMAIN_PATH}.com
      #- VIRTUAL_PATH=/${FRONTEND_PATH}/
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/${DOMAIN_PATH}/${FRONTEND_PATH}/
      - VIRTUAL_DEST=/
      - VIRTUAL_PORT=${FRONTEND_PORT}
      #- VIRTUAL_PORT=19006
    networks:
      - topDomainProxy

  backend:
    build: Backend
    env_file: .env
    command: npm run start
    volumes:
      - ./Backend/app:/usr/app/
      #- ./Backend/app/build:/usr/app/build
      #- ./Backend/app/node_modules:/usr/app/node_modules
    ports:
      - ${BACKEND_PORT}
    environment:
      #- VIRTUAL_HOST=${DOMAIN_PATH}.com
      #- VIRTUAL_PATH=/${BACKEND_PATH}/
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PATH=/${DOMAIN_PATH}/${BACKEND_PATH}/
      - VIRTUAL_DEST=/
      - VIRTUAL_PORT=${BACKEND_PORT}
    networks:
      - topDomainProxy

networks:
  topDomainProxy:
    external: true
